// OTHERS
export const SPINNING_LOADER_STATUS = "SPINNING_LOADER_STATUS";

// USER
export const SET_USERS = "SET_USERS";
export const SET_USER = "SET_USER";
export const SELECT_USER = "SELECT_USER";
export const REMOVE_USER = "REMOVE_USER";

// POSTS
export const SET_ALL_POSTS = "SET_ALL_POSTS";
export const SET_POSTS_OF_USER = "SET_POSTS_OF_USER";

// ALBUMS
export const SET_ALL_ALBUMS = "SET_ALL_ALBUMS";
export const SET_ALBUMS_OF_USER = "SET_ALBUMS_OF_USER";

// FILTER
export const FILTER_WORD = "FILTER_WORD";
export const SET_POSTS_OF_SELECTED_USERS = "SET_POSTS_OF_SELECTED_USERS";
export const SET_ALBUMS_OF_SELECTED_USERS = "SET_ALBUMS_OF_SELECTED_USERS";

// FILTER POSTS
export const FILTER_POSTS = "FILTER_POSTS";
export const SET_FILTERED_POSTS_LENGTH = "SET_FILTERED_POSTS_LENGTH";

// FILTER ALBUMS
export const FILTER_ALBUMS = "FILTER_ALBUMS";
export const SET_FILTERED_ALBUMS_LENGTH = "SET_FILTERED_ALBUMS_LENGTH";

// PAGINATION
export const PAGINATE_POSTS = "PAGINATE_POSTS";
export const PAGINATE_ALBUMS = "PAGINATE_ALBUMS";
